// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © lucas.natoli

//@version=5
strategy("RSI+BB Short", overlay=true)


// Input del usuario
stopPercent = input(title="Stop Loss %", defval=2.0, tooltip="Porcentaje de cierre a la perdida")
takeProfitPercent = input(title="Take Profit %", defval=3.0, tooltip="Porcentaje de cierre a la ganancia")

bbLength  = input(title="BB Length", defval=20)
bbMult = input(title="BB Mult", defval=2)

rsiLength = input(title="RSI Length", defval=14)
rsiOverbought = input(title="RSI Overbought Level", defval=70)
rsiOversold = input(title="RSI Oversold Level", defval=30)

indicatorsSource = input(title="Origen de precios", defval=close)

// One-time values
var savedShortEntry = 0.0
var savedShortLimit = 0.0
var savedShortStop = 0.0

// Obtener Bollinger Bands
[middle, upper, lower] = ta.bb(indicatorsSource, bbLength, bbMult)
isBBTop = upper < close
isBBBottom = lower > close

// Obtener el RSI
rsiValue = ta.rsi(indicatorsSource, rsiLength)
isRsiOB = rsiValue > rsiOverbought
isRsiOS = rsiValue < rsiOversold

shortSignaled = isBBTop and isRsiOB

if (shortSignaled)
    strategy.entry("Top Short", strategy.short)
    savedShortEntry := close
    savedShortLimit := savedShortEntry - (savedShortEntry * takeProfitPercent / 100)
    savedShortStop := savedShortEntry + (savedShortEntry * stopPercent / 100)



plot(savedShortEntry, "Entry", color=#ff00ff)
plot(savedShortLimit, "Limit", color=#00ff00)
plot(savedShortStop, "Stop", color=#ff0000)


//Salir de la estrategia si se alcanza el ShortSellPrice o el ShortStopLoss
strategy.exit("Top Short Exit", from_entry="Top Short", limit=savedShortLimit, stop=savedShortStop)

